import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { CalendarDays, Check, Circle, Clock3, Focus, FolderKanban, Inbox, LayoutDashboard, Play, Plus, RotateCcw, Trash2, UserRoundCheck } from "lucide-react";
import { useApp } from "../../app/AppContext";
import { WorkspaceShell } from "../../layouts/WorkspaceShell";
import { Badge, Button, Card, CardContent, EmptyState, Input, Progress, Section, Select, Tabs, cn } from "../../components/ui";
import { entities, formatDateTime, text, todayKey } from "../../lib/entities";
import { createExecutionProject, createExecutionTask, createExecutionWaitingItem, isOpenExecutionTask, resolveExecutionWaitingItem, taskMatchesToday, type JsonEntity } from "../../services/core";

type View = "today" | "planner" | "inbox" | "projects" | "waiting" | "focus";
type Status = "todo" | "in_progress" | "waiting" | "done";
const tabs = [{value:"today",label:"Today"},{value:"planner",label:"Planner"},{value:"inbox",label:"Inbox"},{value:"projects",label:"Projects"},{value:"waiting",label:"Waiting"},{value:"focus",label:"Focus"}] as const;

export function ExecutionWorkspace() {
  const { state, session, upsert, remove, loading } = useApp();
  const [params,setParams]=useSearchParams();
  const navigate=useNavigate();
  const requested=params.get("view") as View | null;
  const [view,setView]=useState<View>(tabs.some(x=>x.value===requested)?requested!:"today");
  const [title,setTitle]=useState("");
  const [projectId,setProjectId]=useState("");
  const [projectName,setProjectName]=useState("");
  const [planTask,setPlanTask]=useState("");
  const [planStart,setPlanStart]=useState("");
  const [duration,setDuration]=useState("60");
  const [focusTask,setFocusTask]=useState("");\n  const [waitingTitle,setWaitingTitle]=useState("");\n  const [waitingFor,setWaitingFor]=useState("");
  const [startedAt,setStartedAt]=useState<number|null>(null);
  const [elapsed,setElapsed]=useState(0);
  const tasks=entities(state,"execution.task");
  const projects=entities(state,"execution.project").filter(p=>text(p,"status","active")!=="archived");\n  const waitingItems=entities(state,"execution.waiting_item");
  const open=tasks.filter(isOpenExecutionTask);
  const today=todayKey();
  const todayOpen=open.filter(t=>taskMatchesToday(t,today));
  const unscheduled=open.filter(t=>!t.scheduledStartAt);
  const scheduled=todayOpen.filter(t=>t.scheduledStartAt).sort((a,b)=>text(a,"scheduledStartAt").localeCompare(text(b,"scheduledStartAt")));
  const doneToday=tasks.filter(t=>text(t,"status")==="done"&&text(t,"completedAt").slice(0,10)===today);
  const progress=todayOpen.length+doneToday.length?Math.round(doneToday.length/(todayOpen.length+doneToday.length)*100):0;

  useEffect(()=>{if(!startedAt)return; const tick=()=>setElapsed(Math.floor((Date.now()-startedAt)/1000));tick();const id=window.setInterval(tick,1000);return()=>window.clearInterval(id)},[startedAt]);
  function switchView(next:View){setView(next);setParams({view:next},{replace:true})}
  async function addTask(e:FormEvent){e.preventDefault();if(!session||!title.trim())return;await upsert("execution.task",createExecutionTask(session.user.id,session.session.deviceId,{title,projectId:projectId||null,context:"inbox"}));setTitle("")}
  async function addProject(e:FormEvent){e.preventDefault();if(!session||!projectName.trim())return;await upsert("execution.project",createExecutionProject(session.user.id,session.session.deviceId,{name:projectName}));setProjectName("")}\n  async function addWaiting(e:FormEvent){e.preventDefault();if(!session||!waitingTitle.trim()||!waitingFor.trim())return;await upsert("execution.waiting_item",createExecutionWaitingItem(session.user.id,session.session.deviceId,{title:waitingTitle,waitingFor}));setWaitingTitle("");setWaitingFor("")}
  async function toggle(task:JsonEntity){const done=text(task,"status")==="done";await upsert("execution.task",{...task,status:done?"todo":"done",completedAt:done?null:new Date().toISOString()})}
  async function status(task:JsonEntity,next:Status){await upsert("execution.task",{...task,status:next,completedAt:next==="done"?new Date().toISOString():null})}
  async function schedule(e:FormEvent){e.preventDefault();const task=tasks.find(t=>t.meta.id===planTask);if(!task||!planStart)return;const start=new Date(planStart);if(Number.isNaN(start.getTime()))return;const mins=Math.max(15,Number(duration)||60);await upsert("execution.task",{...task,scheduledStartAt:start.toISOString(),scheduledEndAt:new Date(start.getTime()+mins*60000).toISOString(),estimatedMinutes:mins,context:null});setPlanTask("");setPlanStart("")}
  function begin(id:string){setFocusTask(id);setElapsed(0);setStartedAt(Date.now());switchView("focus")}
  async function finish(complete:boolean){const task=tasks.find(t=>t.meta.id===focusTask);if(!task)return;await upsert("execution.task",{...task,actualMinutes:Number(task.actualMinutes??0)+Math.max(1,Math.round(elapsed/60)),status:complete?"done":text(task,"status","todo"),completedAt:complete?new Date().toISOString():task.completedAt??null});setStartedAt(null);setElapsed(0);if(complete)setFocusTask("")}

  return <WorkspaceShell title="Execute" description="计划、时间块、专注执行与复盘" icon={<LayoutDashboard size={17}/>} action={<Button size="sm" variant="outline" onClick={()=>navigate("/app/review")}>Review</Button>}>
    <div className="page-shell">
      <div className="flex flex-col gap-4 border-b pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow">Execution Workspace</div><h1 className="page-title mt-1">今天真正要完成什么？</h1><p className="page-description">从任务池安排时间块，进入专注执行，并把实际投入沉淀到 LifeTrace。</p></div><Tabs value={view} onValueChange={v=>switchView(v as View)} items={tabs}/></div>
      {view==="today"&&<div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-5">
        <Card><CardContent className="pt-5"><form className="grid gap-2 md:grid-cols-[minmax(0,1fr)_180px_auto]" onSubmit={addTask}><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="快速收集一个任务…"/><Select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Inbox / 无项目</option>{projects.map(p=><option key={p.meta.id} value={p.meta.id}>{text(p,"name","Project")}</option>)}</Select><Button disabled={loading||!title.trim()}><Plus size={15}/>添加</Button></form></CardContent></Card>
        <Section title="今日时间轴" description={scheduled.length?scheduled.length+" 个已安排时间块":"还没有安排时间块"} action={<Button size="sm" variant="outline" onClick={()=>switchView("planner")}><CalendarDays size={14}/>Planner</Button>}>{scheduled.length?<Card><div className="divide-y">{scheduled.map(t=><TaskRow key={t.meta.id} task={t} projects={projects} onToggle={toggle} onFocus={begin}/>)}</div></Card>:<EmptyState icon={<Clock3 size={24}/>} title="今天还没有时间块" description="把任务安排到具体时间，Today 才会成为真正的执行计划。" action={<Button variant="outline" onClick={()=>switchView("planner")}>开始规划</Button>}/>}</Section>
        <Section title="今日待办" description={todayOpen.filter(t=>!t.scheduledStartAt).length+" 个未排时间任务"}>{todayOpen.filter(t=>!t.scheduledStartAt).length?<Card><div className="divide-y">{todayOpen.filter(t=>!t.scheduledStartAt).map(t=><TaskRow key={t.meta.id} task={t} projects={projects} onToggle={toggle} onFocus={begin}/>)}</div></Card>:<EmptyState title="没有未安排的今日任务"/>}</Section>
      </div><div className="space-y-4"><Card><CardContent className="pt-5"><div className="eyebrow">今日进度</div><div className="mt-3 flex items-end justify-between"><strong className="text-3xl">{progress}%</strong><span className="text-xs text-muted-foreground">{doneToday.length} 已完成</span></div><Progress value={progress} className="mt-4"/></CardContent></Card><Card><CardContent className="pt-5"><div className="eyebrow">执行闭环</div><div className="mt-3 space-y-3 text-sm text-muted-foreground"><p>1. Inbox 快速收集</p><p>2. Planner 安排时间</p><p>3. Focus 记录实际投入</p><p>4. Review 完成复盘</p></div></CardContent></Card></div></div>}
      {view==="planner"&&<div className="mt-6 grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><Card className="h-fit"><CardContent className="pt-5"><div className="flex items-center gap-2 font-semibold"><Inbox size={16}/>待安排任务</div><div className="mt-4 space-y-2">{unscheduled.slice(0,30).map(t=><button key={t.meta.id} onClick={()=>setPlanTask(t.meta.id)} className={cn("w-full rounded-md border px-3 py-2 text-left text-sm hover:bg-muted",planTask===t.meta.id&&"border-primary bg-accent")}><div className="font-medium">{text(t,"title","任务")}</div><div className="mt-1 text-xs text-muted-foreground">{text(projects.find(p=>p.meta.id===t.projectId),"name","Inbox")} · {Number(t.estimatedMinutes??60)} min</div></button>)}</div></CardContent></Card><div className="space-y-5"><Card><CardContent className="pt-5"><form className="grid gap-3 md:grid-cols-[minmax(0,1fr)_190px_130px_auto]" onSubmit={schedule}><Select required value={planTask} onChange={e=>setPlanTask(e.target.value)}><option value="">选择任务</option>{unscheduled.map(t=><option key={t.meta.id} value={t.meta.id}>{text(t,"title","任务")}</option>)}</Select><Input required type="datetime-local" value={planStart} onChange={e=>setPlanStart(e.target.value)}/><Select value={duration} onChange={e=>setDuration(e.target.value)}><option value="30">30 分钟</option><option value="60">1 小时</option><option value="90">1.5 小时</option><option value="120">2 小时</option></Select><Button>安排</Button></form></CardContent></Card><Section title="今日计划" description={scheduled.length+" 个时间块"}>{scheduled.length?<Card><div className="divide-y">{scheduled.map(t=><TaskRow key={t.meta.id} task={t} projects={projects} onToggle={toggle} onFocus={begin}/>)}</div></Card>:<EmptyState title="今天的时间轴还是空的"/>}</Section></div></div>}
      {view==="inbox"&&<InboxView tasks={open.filter(t=>t.context==="inbox"||(!t.projectId&&!t.dueAt&&!t.scheduledStartAt))} projects={projects} toggle={toggle} begin={begin} removeTask={id=>void remove("execution.task",id)}/>}\n      {view==="projects"&&<Projects projects={projects} tasks={tasks} name={projectName} setName={setProjectName} add={addProject} setStatus={status} begin={begin}/>}\n      {view==="waiting"&&<WaitingView items={waitingItems} title={waitingTitle} waitingFor={waitingFor} setTitle={setWaitingTitle} setWaitingFor={setWaitingFor} add={addWaiting} resolve={item=>void upsert("execution.waiting_item",resolveExecutionWaitingItem(item))} removeItem={id=>void remove("execution.waiting_item",id)}/>}
      {view==="focus"&&<FocusView tasks={open} taskId={focusTask} elapsed={elapsed} running={startedAt!==null} setTask={setFocusTask} start={()=>focusTask&&begin(focusTask)} pause={()=>setStartedAt(null)} resume={()=>setStartedAt(Date.now()-elapsed*1000)} finish={finish}/>}
    </div>
  </WorkspaceShell>
}

function TaskRow({task,projects,onToggle,onFocus}:{task:JsonEntity;projects:JsonEntity[];onToggle(t:JsonEntity):void;onFocus(id:string):void}){return <div className="flex items-center gap-3 px-4 py-3"><button onClick={()=>onToggle(task)} className="flex h-5 w-5 items-center justify-center rounded-full border">{text(task,"status")==="done"?<Check size={13}/>:<Circle size={11} className="opacity-0"/>}</button><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{text(task,"title","任务")}</div><div className="mt-1 flex gap-2 text-xs text-muted-foreground">{task.scheduledStartAt?<span>{formatDateTime(task.scheduledStartAt)}</span>:null}{task.projectId?<span>{text(projects.find(p=>p.meta.id===task.projectId),"name","Project")}</span>:null}</div></div><Button size="sm" variant="ghost" onClick={()=>onFocus(task.meta.id)}><Play size={13}/>开始</Button></div>}

function Projects({projects,tasks,name,setName,add,setStatus,begin}:{projects:JsonEntity[];tasks:JsonEntity[];name:string;setName(v:string):void;add(e:FormEvent):void;setStatus(t:JsonEntity,s:Status):void;begin(id:string):void}){const [selected,setSelected]=useState("");const current=selected||projects[0]?.meta.id||"";const scoped=tasks.filter(t=>!current||t.projectId===current);const columns:[Status,string][]=[["todo","Todo"],["in_progress","Doing"],["waiting","Waiting"],["done","Done"]];return <div className="mt-6 space-y-5"><Card><CardContent className="pt-5"><form className="flex gap-2" onSubmit={add}><Input value={name} onChange={e=>setName(e.target.value)} placeholder="新建 Project…"/><Button disabled={!name.trim()}><Plus size={14}/>创建</Button></form></CardContent></Card><div className="flex gap-2 overflow-x-auto">{projects.map(p=><Button key={p.meta.id} size="sm" variant={current===p.meta.id?"default":"outline"} onClick={()=>setSelected(p.meta.id)}>{text(p,"name","Project")}</Button>)}</div>{projects.length?<div className="grid gap-3 xl:grid-cols-4">{columns.map(([key,label])=><Card key={key}><CardContent className="pt-4"><div className="mb-3 flex justify-between text-sm font-semibold"><span>{label}</span><Badge>{scoped.filter(t=>text(t,"status","todo")===key).length}</Badge></div><div className="space-y-2">{scoped.filter(t=>text(t,"status","todo")===key).map(t=><div key={t.meta.id} className="rounded-md border p-3"><div className="text-sm font-medium">{text(t,"title","任务")}</div><div className="mt-3 flex flex-wrap gap-1">{key!=="todo"&&<Button size="sm" variant="ghost" onClick={()=>setStatus(t,"todo")}><RotateCcw size={12}/></Button>}{key!=="in_progress"&&key!=="done"&&<Button size="sm" variant="outline" onClick={()=>setStatus(t,"in_progress")}>Doing</Button>}{key!=="done"&&<Button size="sm" variant="ghost" onClick={()=>begin(t.meta.id)}><Play size={12}/></Button>}{key!=="done"&&<Button size="sm" variant="ghost" onClick={()=>setStatus(t,"done")}><Check size={12}/></Button>}</div></div>)}</div></CardContent></Card>)}</div>:<EmptyState icon={<FolderKanban size={24}/>} title="先创建一个 Project"/>}</div>}

function FocusView({tasks,taskId,elapsed,running,setTask,start,pause,resume,finish}:{tasks:JsonEntity[];taskId:string;elapsed:number;running:boolean;setTask(v:string):void;start():void;pause():void;resume():void;finish(done:boolean):void}){const task=tasks.find(t=>t.meta.id===taskId);const hh=String(Math.floor(elapsed/3600)).padStart(2,"0"),mm=String(Math.floor(elapsed%3600/60)).padStart(2,"0"),ss=String(elapsed%60).padStart(2,"0");return <div className="mx-auto mt-10 max-w-2xl"><Card><CardContent className="py-10 text-center"><div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-full bg-accent text-primary"><Focus size={22}/></div>{!task?<><h2 className="text-xl font-semibold">选择当前要专注的任务</h2><Select className="mx-auto mt-5 max-w-md" value={taskId} onChange={e=>setTask(e.target.value)}><option value="">选择任务</option>{tasks.map(t=><option key={t.meta.id} value={t.meta.id}>{text(t,"title","任务")}</option>)}</Select><Button className="mt-4" disabled={!taskId} onClick={start}><Play size={15}/>开始专注</Button></>:<><div className="text-sm text-muted-foreground">{text(task,"title","任务")}</div><div className="my-7 font-mono text-6xl font-semibold tracking-tight">{hh}:{mm}:{ss}</div><div className="flex flex-wrap justify-center gap-2">{running?<Button variant="outline" onClick={pause}>暂停</Button>:<Button onClick={resume}><Play size={14}/>继续</Button>}<Button variant="outline" onClick={()=>finish(false)}>结束并记录</Button><Button onClick={()=>finish(true)}><Check size={14}/>完成任务</Button></div></>}</CardContent></Card></div>}


function InboxView({tasks,projects,toggle,begin,removeTask}:{tasks:JsonEntity[];projects:JsonEntity[];toggle(t:JsonEntity):void;begin(id:string):void;removeTask(id:string):void}){return <div className="mt-6"><Section title="Inbox" description={tasks.length+" 个尚未整理的任务"}>{tasks.length?<Card><div className="divide-y">{tasks.map(t=><div key={t.meta.id} className="group flex items-center gap-2"><div className="min-w-0 flex-1"><TaskRow task={t} projects={projects} onToggle={toggle} onFocus={begin}/></div><Button size="icon" variant="ghost" className="mr-2 opacity-60 sm:opacity-0 sm:group-hover:opacity-100" onClick={()=>removeTask(t.meta.id)} aria-label="删除任务"><Trash2 size={14}/></Button></div>)}</div></Card>:<EmptyState icon={<Inbox size={24}/>} title="Inbox 已清空" description="新的想法先快速收集到这里，再在 Planner 中决定什么时候执行。"/>}</Section></div>}

function WaitingView({items,title,waitingFor,setTitle,setWaitingFor,add,resolve,removeItem}:{items:JsonEntity[];title:string;waitingFor:string;setTitle(v:string):void;setWaitingFor(v:string):void;add(e:FormEvent):void;resolve(item:JsonEntity):void;removeItem(id:string):void}){const openItems=items.filter(i=>text(i,"status","open")==="open");const resolved=items.filter(i=>text(i,"status")==="resolved");return <div className="mt-6 space-y-5"><Card><CardContent className="pt-5"><form className="grid gap-2 md:grid-cols-[minmax(0,1fr)_220px_auto]" onSubmit={add}><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="正在等待什么？"/><Input value={waitingFor} onChange={e=>setWaitingFor(e.target.value)} placeholder="等待对象 / 人 / 组织"/><Button disabled={!title.trim()||!waitingFor.trim()}><Plus size={14}/>添加</Button></form></CardContent></Card><Section title="等待中" description={openItems.length+" 项"}>{openItems.length?<Card><div className="divide-y">{openItems.map(i=><div key={i.meta.id} className="flex items-center gap-3 px-4 py-3"><UserRoundCheck size={16} className="text-muted-foreground"/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{text(i,"title","等待事项")}</div><div className="mt-1 text-xs text-muted-foreground">等待：{text(i,"waitingFor","—")}{i.followUpAt?" · 跟进 "+formatDateTime(i.followUpAt):""}</div></div><Button size="sm" variant="outline" onClick={()=>resolve(i)}><Check size={13}/>已解决</Button><Button size="icon" variant="ghost" onClick={()=>removeItem(i.meta.id)}><Trash2 size={14}/></Button></div>)}</div></Card>:<EmptyState title="当前没有等待事项"/>}</Section>{resolved.length?<Section title="最近已解决"><Card><div className="divide-y">{resolved.slice(0,10).map(i=><div key={i.meta.id} className="px-4 py-3 text-sm text-muted-foreground line-through">{text(i,"title","等待事项")}</div>)}</div></Card></Section>:null}</div>}
